#5qs 
# 1 quais os dados de entrada necessários
# 2 o que devo fazer com estes dados
# 3 quais são as restrições deste problema
# qua l é o resultado esperado
# qual é a sequência de passos a ser feitas para chegar ao resultado esperado

# exemplo de função processa mas não retorna algo
def e_maior_de_idade ():
  idade = int(input(" digite sua idade: ")) 
  if idade > 18:
    print(" Maior de idade")
                                        
        #print(" é maior de idade ")
    if idade <18:
        print(" menor de idade")

e_maior_de_idade()


#def pode_entrar_na_festa ():
    #idade = idade = int(input(" digite sua idade: ")) # função que processa e retona algo

   # if idade >=18:
       # return True
   # else:
   #     return False
    

#if pode_entrar_na_festa() == True:
    #print (" Bem vindo a festa ")
#else:
   # print(" vc não pode entrar")

    

    


